name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ۱ . دانلود کدهای پروژه روی سرور گیت‌هاب
      - name: Checkout the code
        uses: actions/checkout@v5

      # ۲. نصب و تنظیم جاوا
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      # ۳. دادن دسترسی اجرایی به فایل gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # ۴. بازسازی فایل Keystore از روی متن امنیتی در ریشه پروژه
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$ENCODED_STRING" | base64 --decode > app/release.jks  

      # ۵. بیلد کردن نسخه AAB برای گوگل پلی و APK برای تلگرام
      - name: Build App Bundle (AAB) & APK
        env:
          KEYSTORE_FILE: release.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#       build apk debug & aab release
#       run: ./gradlew assembleDebug bundleRelease
#       build apk release & aab release
        run: ./gradlew assembleRelease bundleRelease

      # ۶. آپلود و ذخیره فایل APK در گیت‌هاب (Artifacts)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
#          name: ArmenGo-debug-apk
#          path: app/build/outputs/apk/debug/app-debug.apk
          name: ArmenGo-release-apk
          path: app/build/outputs/apk/release/app-release.apk

      # ۷. ارسال خودکار فایل APK به تلگرام
      - name: Send APK to Telegram
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_TO_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: app/build/outputs/apk/release/app-release.apk
#          document: app/build/outputs/apk/debug/app-debug.apk
          message: |
            🚀 نسخه جدید اپلیکیشن EasyLezo با موفقیت بیلد شد!
            
            توسط: ${{ github.actor }}
            کامیت: ${{ github.event.head_commit.message }}

      # ۸. آپلود خودکار نسخه AAB به کانال تست داخلی گوگل پلی
      - name: Upload to Google Play Internal Track
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_KEY }}
          packageName: am.mojtaba.armengo
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed